project:
  output-dir: docs/fr
  render:
    - fr_*.qmd

website:
  title: "Illia Kovalenko"
  navbar:
    background: primary
    search: true
    left:
      - href: fr_index.html
        text: Accueil
      - href: fr_projects.html
        text: Projets
      - href: fr_method.html
        text: Méthode
      - href: fr_cv.html
        text: CV
      - href: fr_contact.html
        text: Contact
    right:
      - text: "English"
        href: ../en/en_index.html
      - text: "Français"
        href: fr_index.html

format:
  html:
    lang: fr-FR
