project:
  output-dir: docs/en
  render:
    - en/*.qmd

website:
  title: "Illia Kovalenko"
  navbar:
    background: primary
    search: true
    left:
      - href: /en/index.html
        text: Home
      - href: /en/projects.html
        text: Projects
      - href: /en/method.html
        text: Method
      - href: /en/cv.html
        text: CV
      - href: /en/contact.html
        text: Contact
    right:
      - text: FR
        href: "javascript:void(0)"

format:
  html:
    lang: en-GB
