project:
  render:
    - fr/*.qmd

website:
  title: "Illia Kovalenko"
  favicon: images/favicon.ico
  navbar:
    logo: images/ik-monogram.svg
    background: primary
    search: true
    left:
      - href: /fr/index.html
        text: Accueil
      - href: /fr/projects.html
        text: Projets
      - href: /fr/method.html
        text: Méthode
      - href: /fr/cv.html
        text: CV
      - href: /fr/contact.html
        text: Contact
    right:
      - text: "English"
        href: /en/index.html
      - text: "Français"
        href: /fr/index.html

format:
  html:
    lang: fr-FR
    output-dir: fr
