project:
  render:
    - index.qmd
    - about.qmd

website:
  favicon: images/favicon.ico
  navbar: false
  search: false

format:
  html:
    theme:
      - cosmo
      - brand
    toc: true
    css: styles.css