project:
  output-dir: docs/fr
  render:
    - fr/*.qmd

website:
  title: "Illia Kovalenko"
  navbar:
    background: primary
    search: true
    left:
      - href: /fr/index.html
        text: Accueil
      - href: /fr/projects.html
        text: Projets
      - href: /fr/method.html
        text: MÃ©thode
      - href: /fr/cv.html
        text: CV
      - href: /fr/contact.html
        text: Contact
    right:
      - text: EN
        href: "javascript:void(0)"

format:
  html:
    lang: fr-FR
