project:
  type: website
  output-dir: docs
  resources:
    - assets

format:
  html:
    theme:
      - cosmo
      - brand
    toc: true
    css: styles.css
    include-after-body:
      text: |
        <script src="/assets/lang-switch.js"></script>

# cd C:\Users\koval\OneDrive\portfolio\illiaskovalenko.github.io
## quarto render
# Depuis PS, 
## git add -A
## git commit -m "Update portfolio"
## git push

