project:
  type: website
  output-dir: docs

format:
  html:
    theme:
      - cosmo
      - brand
    toc: true
    css: styles.css

# cd C:\Users\koval\OneDrive\portfolio\illiaskovalenko.github.io
## quarto render
# Depuis PS, 
## git add -A
## git commit -m "Update portfolio"
## git push

