project:
  type: website
  output-dir: docs

profile:
  group:
    - [def, en, fr]

format:
  html:
    theme:
      - cosmo
      - brand
    toc: true
    css: styles.css
    html-math-method: katex
    include-after-body: []
    html: true


