project:
  output-dir: docs/fr
  render:
    - fr/*.qmd

website:
  title: "Illia Kovalenko"
  navbar:
    background: primary
    search: true
    left:
      - href: /fr/index.html
        text: Accueil
      - href: /fr/projects.html
        text: Projets
      - href: /fr/method.html
        text: Méthode
      - href: /fr/cv.html
        text: CV
      - href: /fr/contact.html
        text: Contact
    right:
      - text: "English"
        href: docs/en/index.html
      - text: "Français"
        href: docs/fr/index.html

format:
  html:
    lang: fr-FR
