project:
  output-dir: docs/en
  render:
    - en_*.qmd

website:
  title: "Illia Kovalenko"
  navbar:
    background: primary
    search: true
    left:
      - href: /en/en_index.html
        text: Home
      - href: /en/en_projects.html
        text: Projects
      - href: /en/en_method.html
        text: Method
      - href: /en/en_cv.html
        text: CV
      - href: /en/en_contact.html
        text: Contact
    right:
      - text: "English"
        href: /en/en_index.html
      - text: "Fran√ßais"
        href: /fr/fr_index.html

format:
  html:
    lang: en-GB
