project:
  type: website
  output-dir: docs

website:
  title: "Illia Kovalenko"
  navbar:
    left:
      - href: index.qmd
        text: Accueil
      - href: projects.qmd
        text: Projets
      - href: methodo.qmd
        text: MÃ©thodologie
      - href: cv.qmd
        text: CV
      - href: contact.qmd
        text: Contact

format:
  html:
    theme:
      - cosmo
      - brand
    toc: true
    css: styles.css
    lang: fr

